### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by dwradcliffe** [aspenmesh/istio-vet#44]
Probably very similar to #40, but for GCP.

**Comment by nrjpoddar** [comment]
Thanks for filing this. It should be an easy fix as per: https://github.com/kubernetes/client-go/issues/242

Will update this issue, once we address it.

Feel free to submit a PR if you want to implement the fix before we can. In https://github.com/aspenmesh/istio-vet/issues/40 I have comments for how to build this project locally.

**Comment by dwradcliffe** [comment]
Yep should be a one line fix. I was unable to get the dependencies updated and build locally to test though.

```
protoc -I/usr/local/include -I. \
		-I/Users/davidradcliffe/src \
		--go_out=:pkg/generated \
		api/v1/note.proto
go install -v ./cmd/... ./pkg/...
github.com/dwradcliffe/istio-vet/pkg/generated/api/v1
# github.com/dwradcliffe/istio-vet/pkg/generated/api/v1
pkg/generated/api/v1/note.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
make: *** [go-build] Error 2
```

**Comment by nrjpoddar** [comment]
Ah I missed few steps:

```go
go install ./vendor/github.com/golang/protobuf/protoc-gen-go
go install ./vendor/github.com/wadey/gocovmerge
```
I’m going to file a bug for adding a Make target initializing all dev dependencies and updating README. Sorry about that.

**Comment by dwradcliffe** [comment]
I also had to `brew install protobuf`

**Comment by nrjpoddar** [comment]
Yep, was just typing that. Copying & pasting links on my phone is much slower. Thanks for working through it. 😄

**Comment by sudomann** [comment]
I just ran into this error. I'm not savvy enough to muck around with building this tool incorporating fixes similar to what others have done when they issue cropped up using their providers.
Is this going to get a fix any time soon?

**Comment by nrjpoddar** [comment]
@sudomann & @dwradcliffe please try with the latest `quay.io/aspenmesh/istio-vet:master` and this issue should be resolved now.

**Comment by sudomann** [comment]
```bash
$ docker run --rm -v $HOME/.kube/config:/root/.kube/config quay.io/aspenmesh/istio-vet:master
No Auth Provider found for name "gcp"
Error: No Auth Provider found for name "gcp"
# ...
```

**Comment by nrjpoddar** [comment]
@sudomann it seems to work for me. You might have a cached version of `quay.io/aspenmesh/istio-vet:master`so please refetch the latest image or use this tag `quay.io/aspenmesh/istio-vet:master-fac74e5`

**Comment by sudomann** [comment]
My fault, I should've thought to do that.
I got the following errors being streamed endlessly to stdout after the container finally ran:
```bash
E0709 19:30:03.630959       1 reflector.go:205] github.com/aspenmesh/istio-vet/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.ConfigMap: Get https://<redacted-ip>/api/v1/configmaps?limit=500&resourceVersion=0: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
E0709 19:30:03.632900       1 reflector.go:205] github.com/aspenmesh/istio-vet/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Namespace: Get https://<redacted-ip>/api/v1/namespaces?limit=500&resourceVersion=0: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
E0709 19:30:03.633379       1 reflector.go:205] github.com/aspenmesh/istio-vet/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Service: Get https://<redacted-ip>/api/v1/services?limit=500&resourceVersion=0: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
E0709 19:30:03.633762       1 reflector.go:205] github.com/aspenmesh/istio-vet/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Pod: Get https://<redacted-ip>/api/v1/pods?limit=500&resourceVersion=0: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
E0709 19:30:03.634644       1 reflector.go:205] github.com/aspenmesh/istio-vet/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Endpoints: Get https://<redacted-ip>/api/v1/endpoints?limit=500&resourceVersion=0: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
```

gcloud missing inside the container?

**Comment by nrjpoddar** [comment]
@sudomann you shouldn't need `gcloud` as long as you run the `gcloud container clusters get-credentials` command locally which should populate the kube config file which you use to run the `istio-vet` container by mounting it as a file.

When you run the `get-credentials` first, kube config should have the access token which will be used by the `istio-vet`.

**Comment by nrjpoddar** [comment]
That's partially correct. I think the container version of the vet will not work as mounting the kube config for GKE clusters always requires access to `gcloud` binary and the path for `gcloud` is set when you run `gcloud container clusters get-credentials` from your local machine in the kube config.

Is it possible for you to run `vet` locally by following these steps: https://github.com/aspenmesh/istio-vet#build-prerequisites. That should unblock you for now until we come up with a long term fix.

**Comment by sudomann** [comment]
Understood, thank you
