### ISSUE TITLE
Seems like prefix checking isn't working properly

### ISSUE THREAD

**Issue by sdake** [aspenmesh/istio-vet#46]
Hi,

I have a service as follows

```
apiVersion: v1
kind: Service
metadata:
  name: a-0
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 8080
    targetPort: 80
    name: http-two
  - port: 90
    targetPort: 9090
    name: tcp
  - port: 9090
    targetPort: 90
    name: https
  - port: 70
    targetPort: 7070
    name: http2-example
  - port: 7070
    targetPort: 70
    name: grpc
```

Running through istio-vet I get

```
Missing prefix in service - a-0
===============================
WARNING: The service a-0 in namespace default contains port names not prefixed with mesh supported protocols. Consider updating the service port name with one of the mesh recognized prefixes.
```

AFAIK, all of the above prefixes are valid.  I'd look into resolving, but obtaining CLA signatures is difficult in big cos.

Cheers
-steve

**Comment by nrjpoddar** [comment]
Your configuration is correct, issue is with the vetter. `https` was added rather late in Istio as a recognized port prefix, we don't list it: https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/util/util.go#L109

Thanks for filing this and if you are able to submit a PR after working through your CLA, please do!

**Comment by esnible** [comment]
I ran into the same issue today.

I also had multiple ports on my Service and it took some experimentation to figure out that it was the port name "https" that was triggering the warning.  Consider modifying the message to give all or one of the offending port names.

Furthermore, I was unsure if "https" was valid or not.  It took me about 3 minutes to find https://istio.io/docs/setup/kubernetes/prepare/requirements/ which seems to be the list of Istio-supported protocol names for port.  Consider modifying the message to say "See https://istio.io/docs/setup/kubernetes/prepare/requirements/" or similar.

**Comment by nrjpoddar** [comment]
Good idea, we should point to the Istio docs as the authoritative source.
