### ISSUE TITLE
Multiple VirtualServices define the same host

### ISSUE THREAD

**Issue by esnible** [aspenmesh/istio-vet#47]
This ERROR should not be present.

```
ERROR: The VirtualServices bookinfo, httpbin in namespace(s) default, default define the same host, *. A host name can be defined by only one VirtualService. Consider updating the VirtualService(s) to have unique hostnames.
```

Although both my bookinfo and httpbin VS use '*' they are attached to different Gateways.  I have placed the Gateways on different ports.  It should not be a problem to have the same hostname if the gateways are different.

The message wording is difficult to parse.  Perhaps replace with something like

```
ERROR: The VirtualServices bookinfo.default and httpbin.default use the same host, "*". A host name can be used by only one VirtualService. Consider updating the VirtualService(s) to have unique hostnames or use different Gateways.
```

It might be useful to give the errors istio-vet codes like VS001 so that in the future we can look them up.

**Comment by nrjpoddar** [comment]
Thanks @esnible for filing this. I really appreciate your help in exercising these paths and filing issues as you find them.

**Comment by nrjpoddar** [comment]
Fixed by https://github.com/aspenmesh/istio-vet/pull/53 from @BLaurenB
