### ISSUE TITLE
RFE: Allow for multiple VirtualServices in "VirtualServices Define the Same Host" vetter

### ISSUE THREAD

**Issue by gramidt** [aspenmesh/istio-vet#73]
The Istio vet error "A VirtualService must have a unique combination of host and gateway." needs to be updated to allow for multiple VirtualServices defined.

Istio now allows you to do both, 1. match multiple URI's to multiple destinations, merged in one vs or 2. use separate vs for each URI/vs.

**Comment by b-t-g** [comment]
Fixed by #77 .
